# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Very simple test runner using Ubuntu's copy of Boost, rather than downloading
# our own copy. Probably not appropriate for most libraries as they'll
# require a more recent version of Boost, and might worry about accidentaly
# picking up the wrong file.

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev
            - libboost-test-dev
            - libboost-filesystem-dev
            - libboost-regex-dev

matrix:
    include:
      - compiler: gcc
        env: BJAM_TOOLSET=gcc
      #- compiler: gcc
      #  env: BJAM_TOOLSET=gcc-std11
      #- compiler: clang
      #  env: BJAM_TOOLSET=clang
      #- compiler: clang
      #  env: BJAM_TOOLSET=clang-std11

before_script:
    - |
      cat <<EOL > ~/user-config.jam
      using gcc : : g++-4.8 ;
      using gcc : std11 : g++-4.8 --std=c++11 ;
      using clang : : clang++ ;
      using clang : std11 : clang++ --std=c++11 ;
      EOL
    - "echo 'rule boost-install ( libraries * ) { }' > Jamroot.jam"
    - "echo 'project /boost/test ;' >> Jamroot.jam"
    - "echo 'lib boost_unit_test_framework : : <name>libboost_unit_test_framework ;' >> Jamroot.jam"
    - "echo 'project /boost/filesystem ;' >> Jamroot.jam"
    - "echo 'lib boost_filesystem : : <name>libboost_filesystem ;' >> Jamroot.jam"
    - "echo 'project /boost/regex ;' >> Jamroot.jam"
    - "echo 'lib boost_regex : : <name>libboost_regex ;' >> Jamroot.jam"


script:
    - cd ${TRAVIS_BUILD_DIR}
    - cat Jamroot.jam
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
