# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Very simple test runner using Ubuntu's copy of Boost, rather than downloading
# our own copy. Probably not appropriate for most libraries as they'll
# require a more recent version of Boost, and might worry about accidentaly
# picking up the wrong file.

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev
            - libboost-test-dev
            - libboost-filesystem-dev
            - libboost-regex-dev

matrix:
    include:
      - compiler: gcc
        env: BJAM_TOOLSET=gcc
        env: NO_BZIP2=1
      - compiler: gcc
        env: BJAM_TOOLSET=gcc-std11
        env: NO_BZIP2=1
      - compiler: clang
        env: BJAM_TOOLSET=clang
        env: NO_BZIP2=1
      - compiler: clang
        env: BJAM_TOOLSET=clang-std11
        env: NO_BZIP2=1

before_script:
    - |
        echo "using gcc : : g++-4.8 ;" > ~/user-config.jam
        echo "using gcc : std11 : g++-4.8 --std=c++11 ;" >> ~/user-config.jam
        echo "using clang : : clang++ ;" >> ~/user-config.jam
        echo "using clang : std11 : clang++ --std=c++11 ;" >> ~/user-config.jam
    - |
        echo 'rule boost-install ( libraries * ) { }' > Jamroot.jam
        echo 'project /boost/test ;' >> Jamroot.jam
        echo 'lib boost_unit_test_framework : : <name>boost_unit_test_framework ;' >> Jamroot.jam
        echo 'project /boost/system ;' >> Jamroot.jam
        echo 'lib boost_system : : <name>boost_system ;' >> Jamroot.jam
        echo 'project /boost/filesystem ;' >> Jamroot.jam
        echo 'lib boost_filesystem : /boost/system//boost_system : <name>boost_filesystem ;' >> Jamroot.jam
        echo 'project /boost/regex ;' >> Jamroot.jam
        echo 'lib boost_regex : : <name>boost_regex ;' >> Jamroot.jam

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cat Jamroot.jam
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
